# Generated by Django 5.2 on 2025-04-06 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_record_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.car')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.maintenancetask')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='maintenance_tasks',
            field=models.ManyToManyField(related_name='cars', through='myapp.CarMaintenance', to='myapp.maintenancetask'),
        ),
    ]
