# Generated by Django 5.1.7 on 2025-04-07 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_payment_receipt_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='binary_receipt_pdf',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
