version: '3.9'

services:
  db:
    image: mysql:8.0
    container_name: mycar-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mycardb
      MYSQL_USER: mycaruser
      MYSQL_PASSWORD: secret
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./backend-django
    container_name: mycar-backend
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=mycardb
      - DB_USER=mycaruser
      - DB_PASSWORD=secret

  frontend:
    build: ./frontend-angular
    container_name: mycar-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  mysql_data:
